### PR TITLE
track user id in GA for better support

### PR DESCRIPTION
**Pull request by dreamfall**

### CODE REVIEW

**Comment by matthewford** [comment]
TODO: I need to provide the cookie policy updates

**Comment by matthewford** [comment]
@dreamfall we need to add similar copy to to the cookie policy as https://www.universal-credit.service.gov.uk/cookiepolicy/

We then need to allow users to opt-out by dropping another cookie that disables this.

**Comment by matthewford** [comment]
Added a card for this https://trello.com/c/GPbJyASi/655-add-userid-tracking-to-google-analytics

**Comment by dreamfall** [comment]
[[QAE17] Add User_ID tracking to google analytics](https://trello.com/c/GeoqdG6S/1773-qae17-add-userid-tracking-to-google-analytics)

**Pull request merged**
