### PR TITLE
Remove the direct/indirect subquestions from C6.

### PR DESCRIPTION
**Pull request by jaleszek**
Erased as can be too complex for the User.

### CODE REVIEW

**Comment by jaleszek** [comment]
@dreamfall can you take a look please ?

**Comment by dreamfall** [comment]
@jaleszek looks good. Does financial report/pdf export work?

**Comment by jaleszek** [comment]
does financial report == financial summary

**Comment by dreamfall** [comment]
> does financial report == financial summary

yes

**Comment by jaleszek** [comment]
it's fine

**Pull request merged**
