### PR TITLE
Refactoring redundant tables

### PR DESCRIPTION
**Pull request by eritiro**
deleted company_details table and updated admin views and controllers to modify form_answer.document instead.

### CODE REVIEW

**Comment by matthewford** [comment]
@eritiro can we squash some of these fix tests commits?

**Comment by eritiro** [comment]
Done @matthewford

**Comment by matthewford** [comment]
@eritiro still got a couple of spec failures.

**Comment by eritiro** [comment]
@matthewford I've just rerun them and It's passing.

**Comment by matthewford** [comment]
@eritiro this rebased on master? or perhaps @rusllonrails your work is in a different branch, would like to merge in the work to store a version on submission as we are relying on the versions now to preserve the original form.

**Comment by eritiro** [comment]
couldn't rebase (too many conflicts) but I've merged the branch with master's commits

**Comment by matthewford** [comment]
@eritiro @rusllonrails can we extend this:

https://github.com/bitzesty/qae/blob/refactoring-redundant-tables/app/models/form_answer.rb#L8

To make sure we have a version on submission?

**Comment by rusllonrails** [comment]
@matthewford sure -will take a look right after issue with submitted forms with not 100% progress

**Pull request merged**
